### PR TITLE
Mapbox v2

### LINKED ISSUE #203: display() - mapbox hover "help" doesn't display non-numeric data
0.86 (not data set specific)

```
import pixiedust
df=pixiedust.SampleData(2)
display(df)
```

* Select `Map` chart type
* As _keys_ select `Longitude` and `Latitude`
* As _value_ select a numeric field (e.g. `price`) and a non-numeric field (e.g. `name`)
* Choose `mapbox` as _renderer_
* Hover over a marker

### Expected behavior

The hover help/tool tip displays the values for the selected numeric field (e.g. `price`) and non-numeric field (e.g. `name`).

### Actual behavior

The hover help/tool tip displays the values for the selected numeric field (e.g. `price`) only.

### PR DESCRIPTION
**Pull request by rajrsingh**
fixes #203, #460, #607 

This is a re-write of the options dialog for mapping with the Mapbox renderer. 

### Changes

- Replaces key fields with separate latitude and longitude options. These are saved in metadata as `latField` and `lonField`
- Changes value fields to "Mapping Fields" in the UI and restricts it to a single value (but still writes to the `valueField` key in metadata)
- Offers "Extra Fields" -- fields that show in the info hover -- which are saved to `extraFields` metadata
- Changes the name of the renderer to "mapbox-points" to clarify that only point data can be used

### Notes

- `preserveCols` metadata is no longer used and should be removed from the code in all places
- Breaks compatibility with the original mapbox renderer due to the change in metadata

### CODE REVIEW

**Comment by DTAIEB** [comment]
I don't think this PR is ready to merge as we don't have a path to deprecate the current mapbox rendering engine. We should revisit later when we have the resources to properly make the transition

**Comment by rajrsingh** [comment]
Needs more work to integrate with other new work

**Comment by rajrsingh** [comment]
@vabarbosa I need your expertise with this merge. Can you take a look?

**Comment by vabarbosa** [comment]
@rajrsingh it looks like your manual merge removed/didn't include some earlier updates (e.g., #682).

in addition, when i try to run it and display a map i get:
`TypeError: isMap() missing 1 required positional argument: 'handlerId'`

maybe you can break down all the changes into smaller individual updates/PRs. that would make it easier to review, test, and approve/reject the PR.

**Pull request closed without merging**
